spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8050

springdoc:
  api-docs:
    enabled: true
    path: /user/v3/api-docs
  swagger-ui:
    path: /

eureka:
  client:
    preferSameZoneEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    health-check-url-path: /actuator/health

jwt:
  secret: aklsdjmfn908rojknm390ruawioujnKJHBhsdfkljf9783LKJlaskdjnmf
  signature: www.erp.com
  audiences: www.erp.com
  expiration: 86400

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

